---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation exports'
 
Conditions:
  HasNot: !Equals [ 'true', 'false' ]
 
# dummy (null) resource, never created
Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: HasNot
 